name: Daily Availability Test

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 Minutes UTC
  workflow_dispatch:  # So it could be run through GitHub UI

  push:
    branches: 
      - main
    paths: 
      - '**'
      
  repository_dispatch:  #Triggers from other repos
    types: [trigger-tests]
    

jobs:
  availability-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if site is up
        run: |
          curl -Is https://aurora.heyappo.me | head -n 1 | grep "200 OK"
